<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2022/23</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Málaga</span>
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: small">Profs. Manuel J. Castro y Francisco J. Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Práctica número 9</span>
    </b></span></div>

In [1]:
from algorithms import *

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000">
    El objetivo de esta práctica es desarrollar programas <span style="font-family: Courier">Python</span> para calcular autovalores y autovectores de matrices mediante el <span style="color:#FF0000"><b>método de la potencia</b></span> y sus <span style="color:#FF0000"><b>variantes</b></span>.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Recordamos que el algoritmo del <b>método de la potencia</b> para calcular el <b>autovalor dominante</b>, y la <b>dirección de un autovector</b> asociado al mismo, de una matriz $A\in\mathcal{M}_n(\mathbb{K})$, se basa en calcular una sucesión de vectores unitarios (para una cierta norma) $\{X_k\}_{k\in\mathbb{N}}$ y $n$ sucesiones numéricas $\{\lambda^j_k\}_{k\in\mathbb{N}}$ mediante el siguiente algoritmo:
<ul>
    <li>dado $X_0\in\mathbb{C}^n-\{0\}$ unitario;</li>
    <li>para $k=0,1,2,\ldots$, se contruye
\[
Y_{k+1} = A\,X_k \quad \mbox{y} \quad X_{k+1} = \frac{1}{\|Y_{k+1}\|}\,Y_{k+1}\,;
\]
igualmente, siempre que tengan sentido, se calculan
\[
\lambda^j_{k+1} = \frac{(Y_{k+1})_j}{(X_k)_j}\,, \quad j=1,2,\ldots, n\,.
\]</li>
</ul>
    Sabemos también que bajo ciertas hipótesis (autovalor $\lambda_1$ dominante único, excepto multiplicidad, buena elección del vector inicial, etc.) se obtienen resultados de convergencia en el siguiente sentido:
<ul>
    <li>se tiene la convergencia de normas
\[
\lim_{k\to\infty} \|Y_{k+1}\| = \lim_{k\to\infty} \|A\,X_k\| = |\lambda_1|\,;
\]</li>
    <li>se tiene la convergencia del cociente de componentes (cuando tengan sentido)
\[
\lim_{k\to\infty} \lambda^j_k = \lim_{k\to\infty} \frac{(Y_{k+1})_j}{(X_k)_j} = \lambda_1\,, \quad j=1,2,\ldots, n\,;
\]</li>
    <li>se tiene la convergencia de los vectores
\[
\lim_{k\to\infty} \left( \frac{\bar{\lambda}_1}{|\lambda_1|} \right)^k X_k
\]
hacia un autovector asociado al autovalor $\lambda_1$.</li>
</ul>
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Elaboramos a continuación un programa que implementa el algoritmo del método de la potencia. Dicho programa, de nombre <span style="font-family: Courier">potencia()</span>, tiene como argumentos de entrada, por este orden, la matriz <span style="font-family: Courier">A</span>, el vector inicial con el que comenzar las iteraciones <span style="font-family: Courier,monospace">X</span>, la norma <span style="font-family: Courier">norma</span> con la que realizar el proceso de normalización, el número máximo de iteraciones <span style="font-family: Courier">itermax</span> superadas las cuales el proceso se detendrá, y la tolerancia <span style="font-family: Courier">tol</span> que establece el test de parada. En caso de éxito, los parámtros de salida son una variable booleana indicando que efectivamente se ha alcanzado una situación de convergencia (en caso contrario se envía un mensaje explicativo de error), así como los últimos valores calculados de la sucesión de las normas de $Y_k$, de las sucesiones $\lambda^j_k$, $j=1,2,\ldots,n$ y de los vectores $X_k$.
    <br>
    En el algoritmo implementado se realizarán iteraciones mientras que el número de iteraciones sea inferior al máximo establecido dado y el error sea superior o igual a la tolerancia dada, calculándose el error sobre el valor absoluto de la diferencia de las normas de $Y_{k+1}$ e $Y_k$. En un primer momento podemos hacer que el programa imprima bastante información durante las iteraciones; una vez que se conozca el funcionamiento del mismo, puede ser interesante imprimir menos información.
    </span></div>

In [2]:
def potencia(A, X, norma, itermax, tol):
    m, n = shape(A)
    r, s = shape(X)
    if m != n or n != r or s != 1:
        return False, 'ERROR potencia: no se ejecuta el programa.', 0, 0
    k = 0
    error = 1.
    normaold = 0.
    if A.dtype == complex or X.dtype == complex:
        lambdas = zeros(n, dtype=complex)
    else:
        lambdas = zeros(n, dtype=float)
    while k < itermax and error >= tol:
        k = k+1
        Y = A@X
        normanew = norm(Y, ord=norma)
        error = abs(normanew - normaold)
        for i in range(n):
            if abs(X[i, 0]) >= 1.e-100:
                lambdas[i] = Y[i, 0]/X[i, 0]
            else:
                lambdas[i] = 0.
        X = Y/normanew
        print('Iteración: k = ', k)
        print('Norma: ||A*X_k|| = ', normanew)
#        print('Lambdas: lambdas_k = \n', lambdas)
#        print('Vectores: X_k = \n', X)
        normaold = normanew
    if k == itermax and error >= tol:
        return False, 'ERROR potencia: no se alcanza convergencia.', 0, 0
    else:
        print('Método de la potencia: convergencia numérica alcanzada.')
        return True, normanew, lambdas, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 1.</b></span> Dada la matriz
\[
A = \left( \begin{array}{rrrr} -2 & 3 & -3 & 11 \\ -8 & 9 & -12 & 20 \\ -3 & 3 & -6 & 15 \\ -3 & 3 & -3 & 12 \end{array} \right)\,,
\]
calcular mediante el método de la potencia, si es posible, su autovalor dominante y un autovector asociado. Utilizar la norma infinito y tomar como vector inicial el primer vector de la base canónica de $\mathbb{C}^4$. Podemos poner un límite de 200 iteraciones y una tolerancia de $10^{-12}$.
    </span></div>

In [1]:
A = array([[-2, 3, -3, 11.9], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = ", A)
X0 = array([[1], [0], [0], [0]])
print("X_0 = ", X0)
exito, normas, lambdas, X = potenciades(A, X0,-1j, inf, 900, 1e-9)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

NameError: name 'array' is not defined

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Una variante del método de la potencia es el <b>método de la potencia inversa</b>, que consiste en aplicar el método de la potencia a la matriz $A^{-1}$, en caso de que la misma exista (en caso contrario significa que es singular, y por tanto $\lambda=0$ es autovalor).
    <br>
    Elaboramos a continuación un programa, de nombre <span style="font-family: Courier">potenciainv()</span>, con los mismos parámetros de entrada y de salida que el anterior, que implemente dicho algoritmo.
    <br>
    Notamos que en la implementación utilizaremos el método $L\,U$ para calcular la solución de $Y_{k+1}=A^{-1}\,X_k$, por lo que habría que hacer una única llamada al principio al programa <span style="font-family: Courier">facto_lu()</span> y llamadas a los programas <span style="font-family: Courier">descenso1()</span> y <span style="font-family: Courier">remonte</span> en cada iteración.
    </span></div>

In [4]:
def potenciainv(A, X, norma, itermax, tol):
    m, n = shape(A)
    r, s = shape(X)
    if m != n or n != r or s != 1:
        return False, 'ERROR potenciainv: no se ejecuta el programa.', 0, 0
    exito, LU = facto_lu(A)
    if not exito:
        return False, 'ERROR potenciainv: sin factorización LU.', 0, 0
    k = 0
    error = 1.
    normaold = 0.
    if A.dtype == complex or X.dtype == complex:
        lambdas = zeros(n, dtype=complex)
    else:
        lambdas = zeros(n, dtype=float)
    while k < itermax and error >= tol:
        k = k+1
        exito, Y = descenso1(LU, X)
        exito, Y = remonte(LU, Y)
        if not exito:
            return False, 'ERROR potenciainv: sin factorización LU.', 0, 0
        normanew = norm(Y, ord=norma)
        error = abs(normanew - normaold)
        for i in range(n):
            if abs(X[i, 0]) >= 1e-100:
                lambdas[i] = Y[i, 0]/X[i, 0]
            else:
                lambdas[i] = 0.
        X = Y/normanew
        print('Iteración: k = ', k)
        print('Norma: ||A-1*X_k|| = ', normanew)
#        print('Lambdas: lambdas_k = ', lambdas)
#        print('Vectores: X_k = ', X)
        normaold = normanew
    if k == itermax and error >= tol:
        return False, 'ERROR potenciainv: no se alcanza convergencia.', 0, 0
    else:
        print('Método de la potencia inversa: convergencia numérica alcanzada.')
        return True, normanew, lambdas, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 2.</b></span> Para la matriz dada en el ejercicio anterior, calcular mediante el método de la potencia inversa, si es posible, su autovalor de módulo menor y un autovector asociado. Utilizar los mismos datos iniciales que en el ejercicio anterior.
    </span></div>

In [5]:
A = array([[-2, 3, -3, 11], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = ", A)
X0 = array([[1], [0], [0], [0]])
print("X_0 = ", X0)
exito, normas, lambdas, X = potenciainv(A, X0, inf, 200, 1e-12)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

A =  [[ -2   3  -3  11]
 [ -8   9 -12  20]
 [ -3   3  -6  15]
 [ -3   3  -3  12]]
X_0 =  [[1]
 [0]
 [0]
 [0]]
Iteración: k =  1
Norma: ||A-1*X_k|| =  1.0555555555555558
Iteración: k =  2
Norma: ||A-1*X_k|| =  0.9619883040935673
Iteración: k =  3
Norma: ||A-1*X_k|| =  0.9880108071597431
Iteración: k =  4
Norma: ||A-1*X_k|| =  0.9973698702975748
Iteración: k =  5
Norma: ||A-1*X_k|| =  0.9994927906457691
Iteración: k =  6
Norma: ||A-1*X_k|| =  0.9999078963436698
Iteración: k =  7
Norma: ||A-1*X_k|| =  0.9999838116923525
Iteración: k =  8
Norma: ||A-1*X_k|| =  0.9999972089830678
Iteración: k =  9
Norma: ||A-1*X_k|| =  0.9999995245045199
Iteración: k =  10
Norma: ||A-1*X_k|| =  0.999999919603527
Iteración: k =  11
Norma: ||A-1*X_k|| =  0.9999999864731213
Iteración: k =  12
Norma: ||A-1*X_k|| =  0.9999999977313572
Iteración: k =  13
Norma: ||A-1*X_k|| =  0.9999999996203193
Iteración: k =  14
Norma: ||A-1*X_k|| =  0.999999999936545
Iteración: k =  15
Norma: ||A-1*X_k|| =  0.9999999999894047
I

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Otra variante del método de la potencia es el método de la <b>potencia desplazada</b>, que consiste en aplicar el método de la potencia a la matriz $A-\mu\,I$, donde $\mu\in\mathbb{C}$ es un valor dado que nos permite mover la escala de los autovalores para localizar otros. Evidentemente se puede combinar el método de la potencia desplazada, con el método de la potencia inversa, dando lugar al método de la <b>potencia desplazada inversa</b>, que nos permite calcular el más próximo al valor de $\mu$.
    <br>
    Los programas <span style="font-family: Courier">potenciades()</span> y <span style="font-family: Courier">potenciadesinv()</span> implementan dichos algoritmos; dichos programas deben tener un parámetro de entrada adicional, que es el valor de $\mu$ (que lo ponemos como tercer argumento de entrada).
    </span></div>

In [6]:
def potenciades(A, X, des, norma, itermax, tol):
    m, n = shape(A)
    r, s = shape(X)
    if m != n or n!= r or s != 1:
        return False, 'ERROR potenciades: no se ejecuta el programa.', 0, 0
    B = A - des*eye(n)
    exito, normanew, lambdas, X = potencia(B, X, norma, itermax, tol)
    return exito, normanew, lambdas, X 

In [7]:
def potenciadesinv(A, X, des, norma, itermax, tol):
    m, n = shape(A)
    r, s = shape(X)
    if m != n or n!= r or s != 1:
        return False, 'ERROR potenciadesinv: no se ejecuta el programa.', 0, 0
    B = A - des*eye(n)
    exito, normanew, lambdas, X = potenciainv(B, X, norma, itermax, tol)
    return exito, normanew, lambdas, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3.</b></span> Para la misma matriz dada en los ejercicios anteriores, calcular mediante el método de la potencia desplazada y sus variantes toda la información posible sobre sus autovalores y autovectores.
    </span></div>

In [8]:
A = array([[-2, 3, -3, 11], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = ", A)
X0 = array([[0], [0], [1], [0]])
print("X_0 = ", X0)
exito, normas, lambdas, X = potenciades(A, X0, 9, inf, 200, 1e-10)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

A =  [[ -2   3  -3  11]
 [ -8   9 -12  20]
 [ -3   3  -6  15]
 [ -3   3  -3  12]]
X_0 =  [[0]
 [0]
 [1]
 [0]]
Iteración: k =  1
Norma: ||A*X_k|| =  15.0
Iteración: k =  2
Norma: ||A*X_k|| =  10.2
Iteración: k =  3
Norma: ||A*X_k|| =  11.470588235294118
Iteración: k =  4
Norma: ||A*X_k|| =  11.86153846153846
Iteración: k =  5
Norma: ||A*X_k|| =  11.964980544747082
Iteración: k =  6
Norma: ||A*X_k|| =  11.991219512195123
Iteración: k =  7
Norma: ||A*X_k|| =  11.997803270685868
Iteración: k =  8
Norma: ||A*X_k|| =  11.999450717119316
Iteración: k =  9
Norma: ||A*X_k|| =  11.999862672993881
Iteración: k =  10
Norma: ||A*X_k|| =  11.999965667855577
Iteración: k =  11
Norma: ||A*X_k|| =  11.999991416939338
Iteración: k =  12
Norma: ||A*X_k|| =  11.9999978542333
Iteración: k =  13
Norma: ||A*X_k|| =  11.999999463558229
Iteración: k =  14
Norma: ||A*X_k|| =  11.999999865889551
Iteración: k =  15
Norma: ||A*X_k|| =  11.999999966472387
Iteración: k =  16
Norma: ||A*X_k|| =  11.999999991618097
It

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4.</b></span> Utilizando el método de la potencia y sus variantes, calcular todas la información posible sobre los autovalores y autovectores de las matrices siguientes:
\[
A = \left( \begin{array}{rrrr} 9 & 1 & -2 & 1 \\ 1 & 8 & -3 & -2 \\ -2 & -3 & 7 & -1 \\ 1 & -2 & -1 & 6 \end{array} \right)
\quad
A = \left( \begin{array}{rrrr} 1 & -1 & 3 & 4 \\ -1 & 4 & 0 & -1 \\ 3 & 0 & 0 & -3 \\ 4 & -1 & -3 & 1 \end{array} \right)
\quad
A = \left( \begin{array}{rrrr} 1 & 2 & 3 & 4 \\ 2 & 1 & 4 & 3 \\ 3 & 4 & 1 & 2 \\ 4 & 3 & 2 & 1 \end{array} \right)
\]
    </span></div>

In [45]:
A = array([[1, -1, 3, 4], [-1, 4, 0, -1], [3, 0, 0, -3], [4, -1, -3, 1]])
print("A = ", A)
X0 = array([[-1], [1], [1], [-1]])
print("X_0 = ", X0)
exito, normas, lambdas, X = potencia(A, X0, inf, 200, 1e-12)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

exito, normas, lambdas, X = potenciades(A, X0,10, inf, 200, 1e-12)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

A =  [[ 1 -1  3  4]
 [-1  4  0 -1]
 [ 3  0  0 -3]
 [ 4 -1 -3  1]]
X_0 =  [[-1]
 [ 1]
 [ 1]
 [-1]]
Iteración: k =  1
Norma: ||A*X_k|| =  9.0
Iteración: k =  2
Norma: ||A*X_k|| =  5.0
Iteración: k =  3
Norma: ||A*X_k|| =  6.6
Iteración: k =  4
Norma: ||A*X_k|| =  5.7272727272727275
Iteración: k =  5
Norma: ||A*X_k|| =  6.142857142857142
Iteración: k =  6
Norma: ||A*X_k|| =  5.930232558139535
Iteración: k =  7
Norma: ||A*X_k|| =  6.035294117647059
Iteración: k =  8
Norma: ||A*X_k|| =  5.982456140350877
Iteración: k =  9
Norma: ||A*X_k|| =  6.008797653958945
Iteración: k =  10
Norma: ||A*X_k|| =  5.995607613469985
Iteración: k =  11
Norma: ||A*X_k|| =  6.002197802197802
Iteración: k =  12
Norma: ||A*X_k|| =  5.998901501281582
Iteración: k =  13
Norma: ||A*X_k|| =  6.000549349935909
Iteración: k =  14
Norma: ||A*X_k|| =  5.999725350178522
Iteración: k =  15
Norma: ||A*X_k|| =  6.00013733119707
Iteración: k =  16
Norma: ||A*X_k|| =  5.999931335973083
Iteración: k =  17
Norma: ||A*X_k|| =  6.