<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2022/23</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Málaga</span>
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: small">Profs. Manuel J. Castro y Francisco J. Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Práctica número 10</span>
    </b></span></div>

In [1]:
from algorithms import *

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000">
    Se considera el sistema de ecuaciones lineales $A\,X=B$, donde 
\[
A = \left( \begin{array}{rrrrr}
-33 & 36 & -27 & 18 & -9\\
-33 & 51 & -45 & 30 & -15\\
-19 & 38 & -45 & 34 & -17\\
-9 & 18 & -27 & 27 & -15\\
-3 & 6 & -9 & 12 & -9
\end{array} \right) \quad X = \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_5
\end{array} \right) \quad B = \left( \begin{array}{c}
120 \\ 186\\ 162\\ 99 \\ 36
\end{array} \right)
\]
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 1.</b></span> Al aplicar el método de Gauss con estrategia de pivot parcial al sistema anterior, se obtiene un sistema triangular superior equivalente, que posteriormente se resuelve mediante un proceso de remonte. Escribir dicho sistema triangular superior.
    </span></div>

In [2]:
A = array([[-33, 36, -27, 18, -9], [-33, 51,-45, 30, -15], [ -19, 38, -45, 34, -17], [ -9, 18, -27, 27, -15],
           [ -3, 6, -9, 12, -9]])
print("A = ", A)

A =  [[-33  36 -27  18  -9]
 [-33  51 -45  30 -15]
 [-19  38 -45  34 -17]
 [ -9  18 -27  27 -15]
 [ -3   6  -9  12  -9]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 2.</b></span> Escribir la solución de dicho sistema, resuelto mediante el método de Gauss con estrategia de pívot parcial.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3.</b></span> Obtener toda la información que sea posible sobre los autovalores y autovectores de la matriz A, utilizando única y exclusivamente el método de la potencia, el método de la potencia inversa, y el método de la potencia desplazada inversa con desplazamiento de $9$, en los tres casos tomando como vector inicial el primer vector de la base canónica.
    <br>
    Indicar también la localización de los autovalores que aún faltan por calcular. Se valorará positivamente la corrección de los razonamientos a partir de la información disponible.
    </span></div>

In [6]:
X0 = array([[1], [0], [0], [0], [0]])
print("X_0 = ", X0)
exito, normas, lambdas, X = potencia(A, X0, inf, 900, 1e-9)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

# X1 = array([[1],[1/2],[0],[0],[0]])
# l = -15
# A@X1 - l*X1

X_0 =  [[1]
 [0]
 [0]
 [0]
 [0]]
Iteración: k =  1
Norma: ||A*X_k|| =  33.0
Iteración: k =  2
Norma: ||A*X_k|| =  8.454545454545459
Iteración: k =  3
Norma: ||A*X_k|| =  24.290322580645167
Iteración: k =  4
Norma: ||A*X_k|| =  10.410358565737049
Iteración: k =  5
Norma: ||A*X_k|| =  20.290470723306584
Iteración: k =  6
Norma: ||A*X_k|| =  11.871159395688322
Iteración: k =  7
Norma: ||A*X_k|| =  18.16279867873538
Iteración: k =  8
Norma: ||A*X_k|| =  12.910366964026316
Iteración: k =  9
Norma: ||A*X_k|| =  16.94228378647604
Iteración: k =  10
Norma: ||A*X_k|| =  13.624305569930472
Iteración: k =  11
Norma: ||A*X_k|| =  16.21168253868798
Iteración: k =  12
Norma: ||A*X_k|| =  14.103104170121957
Iteración: k =  13
Norma: ||A*X_k|| =  15.763147589970874
Iteración: k =  14
Norma: ||A*X_k|| =  14.419039184440752
Iteración: k =  15
Norma: ||A*X_k|| =  15.483494752842743
Iteración: k =  16
Norma: ||A*X_k|| =  14.625282461955326
Iteración: k =  17
Norma: ||A*X_k|| =  15.307454605969712
Iteració

In [7]:
exito, normas, lambdas, X = potenciainv(A, X0, inf, 900, 1e-9)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

Iteración: k =  1
Norma: ||A-1*X_k|| =  0.22222222222222202
Iteración: k =  2
Norma: ||A-1*X_k|| =  0.12499999999999974
Iteración: k =  3
Norma: ||A-1*X_k|| =  0.4999999999999997
Iteración: k =  4
Norma: ||A-1*X_k|| =  0.2777777777777779
Iteración: k =  5
Norma: ||A-1*X_k|| =  0.36666666666666653
Iteración: k =  6
Norma: ||A-1*X_k|| =  0.31818181818181823
Iteración: k =  7
Norma: ||A-1*X_k|| =  0.3412698412698412
Iteración: k =  8
Norma: ||A-1*X_k|| =  0.32945736434108525
Iteración: k =  9
Norma: ||A-1*X_k|| =  0.3352941176470588
Iteración: k =  10
Norma: ||A-1*X_k|| =  0.3323586744639377
Iteración: k =  11
Norma: ||A-1*X_k|| =  0.333822091886608
Iteración: k =  12
Norma: ||A-1*X_k|| =  0.3330893118594436
Iteración: k =  13
Norma: ||A-1*X_k|| =  0.33345543345543344
Iteración: k =  14
Norma: ||A-1*X_k|| =  0.33327230562675453
Iteración: k =  15
Norma: ||A-1*X_k|| =  0.33336385277421715
Iteración: k =  16
Norma: ||A-1*X_k|| =  0.333318075009918
Iteración: k =  17
Norma: ||A-1*X_k|| =  0.

In [26]:
exito, normas, lambdas, X = potenciadesinv(A, X0, -7, inf, 900, 1e-9)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

Iteración: k =  1
Norma: ||A-1*X_k|| =  0.5607287449392749
Iteración: k =  2
Norma: ||A-1*X_k|| =  0.4390374018912903
Iteración: k =  3
Norma: ||A-1*X_k|| =  0.5087678302723405
Iteración: k =  4
Norma: ||A-1*X_k|| =  0.4988722818987723
Iteración: k =  5
Norma: ||A-1*X_k|| =  0.5001530051647011
Iteración: k =  6
Norma: ||A-1*X_k|| =  0.4999786653903456
Iteración: k =  7
Norma: ||A-1*X_k|| =  0.5000030510677869
Iteración: k =  8
Norma: ||A-1*X_k|| =  0.49999955495713894
Iteración: k =  9
Norma: ||A-1*X_k|| =  0.500000065905108
Iteración: k =  10
Norma: ||A-1*X_k|| =  0.49999999013055546
Iteración: k =  11
Norma: ||A-1*X_k|| =  0.5000000014899791
Iteración: k =  12
Norma: ||A-1*X_k|| =  0.49999999977376475
Iteración: k =  13
Norma: ||A-1*X_k|| =  0.5000000000344936
Método de la potencia inversa: convergencia numérica alcanzada.
Convergencia de las normas:  0.5000000000344936
Convergencia de los cocientes: [-0.12500221 -0.49999996 -0.5        -0.49993897  0.25000012]
Convergencia de los ve

In [33]:
X1 = array([[1],[1/2],[0],[0],[0]])
l1 = -15
X2 = array([[0],[0],[0],[1/2],[1]])
l2 = -3
X3 = array([[-1/2],[-1],[-1/2],[0],[0]])
l3 = 12
X4 = array([[0],[0],[1/2],[1],[1/2]])
l4 = 6

X5 = array([[0],[-1/2],[-1],[-1/2],[0]])
l5 = -9

print("Comprobaciones:")
print("AX1+15X1=", A@X1 - l1*X1)
print("AX2+15X2=", A@X2 - l2*X2)
print("AX3+15X3=", A@X3 - l3*X3)
print("AX4+15X4=", A@X4 - l4*X4)
print("AX5+15X5=", A@X5 - l5*X5)

Comprobaciones:
AX1+15X1= [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
AX2+15X2= [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
AX3+15X3= [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
AX4+15X4= [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
AX5+15X5= [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4.</b></span> Construir una matriz de orden $𝑛=5$, pentadiagonal, cuyos elementos diagonales valgan 4, y los elementos de las dos diagonales superiores e inferiores $−1$. Tomando como vector inicial aquel que tiene todas sus componentes igual a 1, y aplicando el método de la potencia, calcular su autovalor de módulo mayor y menor; calcular también $cond_2(𝐴)$. Ídem para $𝑛=20$.
    </span></div>

In [62]:
M = diag([4]*5)+diag([-1]*4,1)+diag([-1]*4,-1)+diag([-1]*3,2)+diag([-1]*3,-2)
print(M)

vec = array([[1],[1],[1]])
print(diag([1]*2,-1)+diag([1]*3,0)+diag([1]*2,1))
def vdiag(v, trans=True):
    n,m=shape(v)
    print(n)
    if n%2 == 0:
        return False
    else:
        m = zeros((int(n),int(n)))
        for i in range(n):
            d = int(i-(n-1)/2)
            print(d)
            print(v[i])
            print(n-abs(d))
            print(m)
            di = diag(v[i]*(n-abs(d)), d)
            print(di)
            m = m + diag(v[i]*(n-abs(d)), d)
        return m
print(vdiag(vec))
X0 = array([[1],[1],[1],[1],[1]])
print("X_0 = ", X0)
exito, normas, lambdas, X = potencia(conjugada(A)@A, X0, inf, 900, 1e-9)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)
print(pow(lambdas,1/2))
exito, normas, lambdas, X = potenciainv(conjugada(A)@A, X0, inf, 900, 1e-9)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

print(pow(lambdas,-1/2))

[[ 4 -1 -1  0  0]
 [-1  4 -1 -1  0]
 [-1 -1  4 -1 -1]
 [ 0 -1 -1  4 -1]
 [ 0  0 -1 -1  4]]
[[1 1 0]
 [1 1 1]
 [0 1 1]]
3
-1
[1]
2
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [2 0]]


ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 5.</b></span> Dadas las matrices
\[
A = \left( \begin{array}{rrrr}
9 & 1 & -2 & 1 \\ 1 & 8 & -3 & 2 \\ -2 & -3 & 7 & -1 \\ 1 & -2 & -1 & 6
\end{array} \right) \quad A = \left( \begin{array}{rrrr}
9 & 1 & -2 & 1 \\ 1 & 8 & -3 & -2 \\ -2 & -3 & 7 & -1 \\ 1 & -2 & -1 & 6
\end{array} \right)
\]
\[
A = \left( \begin{array}{rrrr}
1 & 2 & 3 & 4 \\ 2 & 1 & 4 & 3 \\ 3 & 4 & 1 & 2 \\ 4 & 3 & 2 & 1
\end{array} \right)
\]
\[
A = \left( \begin{array}{rrrr}
1 & -1 & 3 & 4 \\ -1 & 4 & 0 & -1 \\ 3 & 0 & 0 & -3 \\ 4 & -1 & -3 & 1
\end{array} \right) \quad A = \left( \begin{array}{rrrr}
0 & 1 & -2 & 3 \\ -1 & 0 & 4 & -5 \\ 2 & -4 & 0 & 6 \\ -3 & 5 & -6 & 0
\end{array} \right)
\]
calcular mediante el método de la potencia y sus variantes toda la información posible sobre sus autovalores y autovectores.
    </span></div>